[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
/home/aaderevyagin/airi_final/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:619: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
/home/aaderevyagin/airi_final/venv/lib/python3.10/site-packages/gymnasium/core.py:311: UserWarning: [33mWARN: env.set_seed to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.set_seed` for environment variables or `env.get_wrapper_attr('set_seed')` that will search the reminding wrappers.
  logger.warn(
  0%|                                                                                                                     | 0/20000 [00:01<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/aaderevyagin/airi_final/airi-screening-part-1/algorithms/generation_baselines/a2c.py", line 153, in calc_loss_on_episode
    action, action_log_prob, critic_output = pick_action_and_get_critic_values(model.actor, model.critic, state, config)
  File "/home/aaderevyagin/airi_final/airi-screening-part-1/algorithms/generation_baselines/a2c.py", line 181, in pick_action_and_get_critic_values
    action_distribution = Categorical(actor_output)
  File "/home/aaderevyagin/airi_final/venv/lib/python3.10/site-packages/torch/distributions/categorical.py", line 70, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/aaderevyagin/airi_final/venv/lib/python3.10/site-packages/torch/distributions/distribution.py", line 68, in __init__
    raise ValueError(
ValueError: Expected parameter probs (Tensor of shape (1, 5)) of distribution Categorical(probs: torch.Size([1, 5])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[ 0.8224, -0.4554,  0.7376, -1.5734,  1.4688]], grad_fn=<DivBackward0>)
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aaderevyagin/airi_final/airi-screening-part-1/./scripts/data_generation.py", line 181, in <module>
    main()
  File "/home/aaderevyagin/airi_final/venv/lib/python3.10/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/aaderevyagin/airi_final/airi-screening-part-1/./scripts/data_generation.py", line 173, in main
    train_tasks = generate_histories(generation_config, generator_config, train_tasks)
  File "/home/aaderevyagin/airi_final/airi-screening-part-1/./scripts/data_generation.py", line 60, in generate_histories
    curr_history = generator.train_from_model(config=generator_config, environment=copy.deepcopy(environment))
  File "/home/aaderevyagin/airi_final/airi-screening-part-1/algorithms/generation_baselines/a2c.py", line 119, in train_from_model
    model, histories = train(config, environment)
  File "/home/aaderevyagin/airi_final/airi-screening-part-1/algorithms/generation_baselines/a2c.py", line 252, in train
    parallel_results = pool.map(calc_loss_on_episode, args)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: Expected parameter probs (Tensor of shape (1, 5)) of distribution Categorical(probs: torch.Size([1, 5])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[ 0.8224, -0.4554,  0.7376, -1.5734,  1.4688]], grad_fn=<DivBackward0>)